version: "3"

services:
    database:
        image: postgres
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=dev
        volumes:
            - ./backend/data/postgres:/var/lib/postgresql/data

    server:
        image: back-prod
        build:
            context: ./backend/
        command: sh -c "npm run migrate:latest && npm run dev"
        volumes:
            - ./backend/:/usr/src/app
        environment:
            - NODE_ENV=development # change to production when new database, change knex file in db
            - DATABASE_URL=postgres://admin:admin@localhost:5432/auction-house-dev
            - PORT=3001
        ports:
            - 3001:3001
        depends_on:
            - database
        container_name: back-prod

    client:
        image: front-prod
        build:
            context: ./frontend/
        volumes:
            - ./frontend/:/usr/src/app/
        ports:
            - 3000:80
        container_name: front-prod

    nginx:
        image: nginx
        ports:
            - 80:80
        volumes:
            - ./nginx.conf/:/etc/nginx/nginx.conf:ro
        container_name: nginx
        depends_on:
            - server
            - client
