version: "3"

services:
    app:
        image: front-dev
        build:
            context: ./frontend/
            dockerfile: dev.Dockerfile
        volumes:
            - ./frontend/:/usr/src/app/
        ports:
            - 3000:3000
        container_name: front-dev
